source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
platform :ios, '9.0'
use_frameworks!

target 'TestAsyncDataPicker' do
    pod 'AsyncDataPicker'
end
